Error during AI analysis: Error: ENOENT: no such file or directory, open 'C:\Users\Gustavo\Desktop\workshop\apps\api\docs\formulario_base.txt'
    at Object.readFileSync (node:fs:441:20)
    at C:\Users\Gustavo\Desktop\workshop\apps\api\src\index.ts:38:31
    at Layer.handleRequest (C:\Users\Gustavo\Desktop\workshop\node_modules\router\lib\layer.js:152:17)
    at next (C:\Users\Gustavo\Desktop\workshop\node_modules\router\lib\route.js:157:13)
    at Route.dispatch (C:\Users\Gustavo\Desktop\workshop\node_modules\router\lib\route.js:117:3)
    at handle (C:\Users\Gustavo\Desktop\workshop\node_modules\router\index.js:435:11)
    at Layer.handleRequest (C:\Users\Gustavo\Desktop\workshop\node_modules\router\lib\layer.js:152:17)
    at C:\Users\Gustavo\Desktop\workshop\node_modules\router\index.js:295:15
    at processParams (C:\Users\Gustavo\Desktop\workshop\node_modules\router\index.js:582:12)
    at next (C:\Users\Gustavo\Desktop\workshop\node_modules\router\index.js:291:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Gustavo\\Desktop\\workshop\\apps\\api\\docs\\formulario_base.txt'
}